#Base amount xp required for each level.
base-xp: 5000

#The rate for increasing xp every level
#Example: if the rate is at 50 & level 1 requires 5000xp Level 2 will require 5050, 5100 and so on
#Set to 0 or -1 to disable
xp-increase-rate: 50


#This section contains the values for how much xp should be given when completing a goal
round-end-lose-xp: 500
round-end-win-xp: 1000

final-kill-xp: 350
kill-xp: 100

break-bed-xp: 175

achievement-earned-xp: 1250